#! /usr/bin/sed -E -i .bak -f
s/(^Matthew\||^matthew\|)/40	/g
s/(^Mark\|)/41	/g
s/(^Luke\|)/42	/g
s/(^John\||^john\|)/43	/g
s/(^Acts\||^acts\|)/44	/g
s/(^Romans\|)/45	/g
s/(^1\|Corinthians\|)/46	/g
s/(^2\|Corinthians\|)/47	/g
s/(^Galatians\|)/48	/g
s/(^Ephesians\|)/49	/g
s/(^Philippians\|)/50	/g
s/(^Colossians\|)/51	/g
s/(^1\|Thessalonians\|)/52	/g
s/(^2\|Thessalonians\|)/53	/g
s/(^1\|Timothy\|)/54	/g
s/(^2\|Timothy\|)/55	/g
s/(^Titus\|)/56	/g
s/(^Philemon\|)/57	/g
s/(^Hebrews\|)/58	/g
s/(^James\|)/59	/g
s/(^1\|Peter\|)/60	/g
s/(^2\|Peter\|)/61	/g
s/(^1\|John\|)/62	/g
s/(^2\|John\|)/63	/g
s/(^3\|John\|)/64	/g
s/(^Jude\|)/65	/g
s/(^Revelation\||^revelation\|)/66	/g
